modules/av-bypass
modules/code-audit
modules/exploitation
modules/intelligence-gathering
modules/mobile-analysis
modules/osx
modules/password-recovery
modules/pivoting
modules/post-exploitation
modules/powershell
modules/pre-engagement
modules/reporting
modules/reversing
modules/threat-modeling
modules/vulnerability-analysis
modules/webshells
modules/windows-tools
modules/wireless
